

export const  disciplineList: Discipline[] = [
    {
      id: '1',
      title_zh: '算法和数据结构',
      title_en: 'Algorithm and Data Structure',
      pic: `/images/1.webp`,
      description: '算法+数据结构',
      belongCategory: 'computerscience',
      last_update: '2021-08-01',
      tags:["1","3","10"],
    },
    {
      id: '2',
      title_zh: '人工智能与机器学习',
      title_en: 'AI and Machine Learning',
      pic: `/images/2.webp`,
      description: '人工智能：让机器模拟人的智能。',
      belongCategory: 'computerscience',
      last_update: '2021-08-01',
      tags:["1","2","3","4",],
    },
    {
      id: '3',
      title_zh: '软件工程',
      title_en: 'Software Engineering',
      pic: `/images/3.webp`,
      description: '软件工程：将软件开发过程规范化的学科。',
      belongCategory: 'computerscience',
      last_update: '2021-08-01',
      tags:["5","6","7"],
    },
    {
      id: '4',
      title_zh: '线性代数',
      title_en: 'Linear Algebra',
      pic: `/images/4.webp`,
      description: '线性代数：研究向量空间的线性变换。',
      belongCategory: 'math',
      last_update: '2021-08-01',
      tags:["1","2","3","4"],
    },
    {
      id: '5',
      title_zh: '概率论',
      title_en: 'Probability Theory',
      pic: `/images/5.webp`,
      description: '概率论：研究随机现象的数学理论的学科。',
      belongCategory: 'math',
      last_update: '2021-08-01',
      tags:["4","6","8"],
    },
    {
      id: '6',
      title_zh: '数理统计',
      title_en: 'Mathematical Statistics',
      pic: `/images/6.webp`,
      description: '数理统计：研究统计学的数学理论的学科。',
      belongCategory: 'math',
      last_update: '2021-08-01',
      tags:["9","12","15"],
    },
    {
      id: '7',
      title_zh: '力学',
      title_en: 'Mechanics',
      pic: `/images/7.webp`,
      description: '力学：研究物体运动的学科。',
      belongCategory: 'physics',
      last_update: '2021-08-01',
      tags:["6","7","14"],
    },
    {
      id: '8',
      title_zh: '电磁学',
      title_en: 'Electromagnetism',
      pic: `/images/8.webp`,
      description: '电磁学：研究电磁场的学科。',
      belongCategory: 'physics',
      last_update: '2021-08-01',
      tags:["17","19"],
    },
    {
      id: '9',
      title_zh: '光学',
      title_en: 'Optics',
      pic: `/images/9.webp`,
      description: '光学：研究光的性质和运动的学科。',
      belongCategory: 'physics',
      last_update: '2021-08-01',
      tags:["20","8"],
    },
  ];